import { values } from "values.slint";

component sidebutton inherits TouchArea {
    button := Rectangle {
        min-height: 15px;
        preferred-height: 40px;
        background: #252525;
        border-width: values.side-button-width;
        border-color: #494949;
        border-radius: values.side-button-radius;
        animate background { duration: 50ms; }
        animate border-radius {
            duration: 300ms;
            easing: ease-out-back;
        }
        animate border-width {
            duration: 300ms;
            easing: ease-out-back;
        }
    }

    states [
        pressed when root.pressed: {
            button.background: #3b3b3b;
        }
        hover when root.has-hover: {
            button.background: #2b2b2b;
        }
    ]
}

export component Sidebar inherits VerticalLayout {
    spacing: 5px;
    width: values.vl-width;
    alignment: start;
    max-height: 30px;
    animate width {
        duration: 300ms;
        easing: ease-out-back;
    }
    // Menu button
    sidebutton {
        Text {
            text: "☰";
            font-size: 20px;
            font-weight: 700;
            color: #ffffff;
            y: +5px;
            x: 11px;
        }

        clicked => {
            if (values.isclicked) {
                values.vl-width = 40px;
                values.side-button-radius = 20px;
                values.side-button-width = 4px;
                values.isclicked = false
            } else {
                values.vl-width = 160px;
                values.side-button-radius = 5px;
                values.side-button-width = 2px;
                values.isclicked = true
            }
        }
    }
    // Main button
    sidebutton {
        Text {
            visible: values.isclicked;
            text: "Main";
            x: + 45px;
        }

        Image {
            source: @image-url("../icons/home.png");
            width: 18px;
            height: 18px;
            x: 11px;
        }

        clicked => {
            if (values.isclicked) {
                values.vl-width = 40px;
                values.side-button-radius = 20px;
                values.side-button-width = 4px;
                values.isclicked = false;
            }
            values.activepage = 0;
        }
    }
    // Devices button
    sidebutton {
        Text {
            visible: values.isclicked;
            text: "Devices";
            x: + 45px;
        }

        Image {
            source: @image-url("../icons/cpu.png");
            width: 18px;
            height: 18px;
            x: 11px;
        }

        clicked => {
            if (values.isclicked) {
                values.vl-width = 40px;
                values.side-button-radius = 20px;
                values.side-button-width = 4px;
                values.isclicked = false;
            }
            values.activepage = 1
        }
    }
    // Logs button
    sidebutton {
        Text {
            visible: values.isclicked;
            text: "Logs";
            x: + 45px;
        }

        Image {
            source: @image-url("../icons/logs.png");
            width: 19px;
            height: 19px;
            x: 11px;
        }

        clicked => {
            if (values.isclicked) {
                values.vl-width = 40px;
                values.side-button-radius = 20px;
                values.side-button-width = 4px;
                values.isclicked = false;
            }
            values.activepage = 2
        }
    }
    // config button
    sidebutton {
        Text {
            visible: values.isclicked;
            text: "Config";
            x: + 45px;
        }

        Image {
            source: @image-url("../icons/config.png");
            width: 18px;
            height: 18px;
            x: 11px;
        }

        clicked => {
            if (values.isclicked) {
                values.vl-width = 40px;
                values.side-button-radius = 20px;
                values.side-button-width = 4px;
                values.isclicked = false;
            }
            values.activepage = 3
        }
    }
}
