
export global values {
    in-out property <length> side-button-radius: 20px;
    in-out property <length> side-button-width: 3px;
    in-out property <int> activepage: 0; //0 main, 1 devices, 2 logs, 3 config
    in-out property <length> vl-width: 40px;
    in-out property <bool> isclicked: false;
    in-out property <length> main-window-height;
    in-out property <length> main-window-width;
}
