
export global values {
    in-out property <length> side-button-radius: 20px;
    in-out property <length> side-button-width: 3px;
    in-out property <int> activepage: 0; //0 main, 1 devices, 2 logs, 3 config
    in-out property <length> vl-width: 40px;
    in-out property <bool> isclicked: false;
    in-out property <length> main-window-height;
    in-out property <length> main-window-width;
    in property <string> time_elapsed: "0s";
    in property <string> total_points:"0";
    in property <string> total_frames: "0";
    in property <string> total_download: "0MB";
    in property <string> total_upload: "0MB";
    in property <string> frames_left: "0";
    in property <string> sheepit_version: "7.25091.0";
    in property <string> manager_version: "0.1.0";
}
