import { values } from "../blocks/values.slint";
import { Theme } from "../blocks/themes.slint";
import { Textf } from "../blocks.slint";


component Device_Box inherits Rectangle {
    background: #181818;
    border-radius: 25px;
    border-color: #353535;
    border-width: 2px;
    width: 175px;
    height: 175px;
    ta := TouchArea { }

    animate background { duration: 150ms; }
    animate width { duration: 150ms; }
    animate height { duration: 150ms; }
    states [
        hover when ta.has-hover: {
            root.background: #242424;
           // root.width: 177px;
          //  root.height: 177px;
        }
    ]
}

export component Devices {
    GridLayout {
        y: + 15px;
        x: + 30px;
        spacing: 15px;
        Row {
            Device-Box {
                GridLayout {
                    y: 40px;
                    x: 40px;
                    width: 50%;
                    height: 70%;
                    Row {
                        Image {
                            source: @image-url("../icons/cpu.svg");
                            colorize: Theme.icon-color;
                            width: 40px;
                            height: 40px;
                        }

                        Textf {
                            text: "16";
                            font-size: 25px;
                            horizontal-alignment: right;
                        }
                    }

                    Row {
                        Image {
                            source: @image-url("../icons/gpu.png");
                            colorize: Theme.icon-color;
                            width: 40px;
                            height: 40px;
                        }

                        Textf {
                            text: "2";
                            font-size: 25px;
                            horizontal-alignment: right;
                        }
                    }

                    Row {
                        Image {
                            source: @image-url("../icons/gpu.svg");
                            colorize: Theme.icon-color;
                            width: 40px;
                            height: 40px;
                        }

                        Textf {
                            text: "80G";
                            font-size: 25px;
                            horizontal-alignment: right;
                        }
                    }
                }

                Rectangle {
                    Textf {
                        text: "Atlas";
                        y: 10px;
                        font-size: 20px;
                    }
                }
            }

            Device-Box {
                GridLayout {
                    y: 40px;
                    x: 40px;
                    width: 50%;
                    height: 70%;
                    Row {
                        Image {
                            source: @image-url("../icons/cpu.svg");
                            colorize: Theme.icon-color;
                            width: 40px;
                            height: 40px;
                        }

                        Textf {
                            text: "16";
                            font-size: 25px;
                            horizontal-alignment: right;
                        }
                    }

                    Row {
                        Image {
                            source: @image-url("../icons/gpu.png");
                            colorize: Theme.icon-color;
                            width: 40px;
                            height: 40px;
                        }

                        Textf {
                            text: "3";
                            font-size: 25px;
                            horizontal-alignment: right;
                        }
                    }

                    Row {
                        Image {
                            source: @image-url("../icons/gpu.svg");
                            colorize: Theme.icon-color;
                            width: 40px;
                            height: 40px;
                        }

                        Textf {
                            text: "40G";
                            font-size: 25px;
                            horizontal-alignment: right;
                        }
                    }
                }
                Rectangle {
                    Textf {
                        text: "Hyperion";
                        y: 10px;
                        font-size: 20px;
                    }
                }

                background: #2c2c2c;
            }
        }

        Row {
            Device-Box {
                Rectangle {
                    Textf {
                        text: "Zephyrus";
                        y: 10px;
                        font-size: 20px;
                    }
                }
            }

            Device-Box {
                Rectangle {
                    Textf {
                        text: "Oceanus";
                        y: 10px;
                        font-size: 20px;
                    }
                }
            }
        }

        Row {
            Device-Box {
                Rectangle {
                    Textf {
                        text: "Triton";
                        y: 10px;
                        font-size: 20px;
                    }
                }
            }

            Device-Box {
                Rectangle {
                    Textf {
                        text: "Helios";
                        y: 10px;
                        font-size: 20px;
                    }
                }
            }
        }
    }
}
